[build]
builder = "nixpacks"

[build.nixpacksSettings]
nixpkgsArchive = "ba913eda2df8eb72147259189d55932012df6301"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
